### DISCUSSION TITLE
[License]: Is it possible to provide redash as bi facility to users in my sql data lakehouse cloud service?

### DISCUSSION THREAD

**Discussion by cloudcheflabs** [getredash/redash#5914] [Q&A]
I am going to launch a SQL Data Lakehouse Cloud Service based on trino.
As BI facility, we provide redash to users to query and explor data in my sql data lakehouse cloud service.
Redash will be deployed on kubernetes with helm chart. The docker image version of redash is redash/redash:10.0.0-beta.b49597 currently.  No code modification of redash is done.
Is there any license problem to provide redash just as bi facility to customers in my sql data lakehouse cloud service?

**Comment by arikfr** [comment]
IANAL but I believe our license allows this usage. Are you planning on using the `MULTI_ORG` functionality?

**Comment by cloudcheflabs** [comment]
I don't understand completely what the `MULTI_ORG` is. As mentioned before, we are using docker image of redash/redash:10.0.0-beta.b49597. I have accessed a redash pod and printed all the redash envs which look like this.
```
env | grep REDASH;

REDASH_LOG_LEVEL=INFO
REDASH_PORT_5000_TCP_ADDR=xxx
REDASH_PORT_5000_TCP_PORT=5000
REDASH_PORT_5000_TCP_PROTO=tcp
REDASH_SERVICE_PORT_REDASH=5000
REDASH_DATABASE_URL=postgresql://xxx
REDASH_SERVICE_HOST=xxx
REDASH_PORT_5000_TCP=tcp://xxx
REDASH_PORT=tcp://xxx
REDASH_SERVICE_PORT=5000
REDASH_WEB_WORKERS=4
```
It seems that there is no env of `REDASH_MULTI_ORG`.

**Reply by arikfr** [reply]
Are you launching a dedicated Redash deployment for each customer? (with its own postgres database, pods, etc)

**Comment by cloudcheflabs** [comment]
Yes. As mentioned before, I am using your docker image of redash/redash:10.0.0-beta.b49597 without code modification. 
I am using redash helm chart (https://github.com/cloudcheflabs/dataroaster/tree/master/components/redash/chart) which belongs to open source dataroaster(https://github.com/cloudcheflabs/dataroaster) which I created.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redash
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: redash
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redash
    spec:
      volumes:
      - name: postgres-for-redash
        persistentVolumeClaim:
          claimName: pgredash-pv-claim
      dnsPolicy: {{ .Values.dnsPolicy }}
      containers:
      - name: redis
        image: redis:5.0-alpine
        ports:
        - containerPort: 6379
      - name:  postgres
        image: postgres:9.5-alpine
        envFrom:
        - configMapRef:
            name: redash-cfg
        volumeMounts:
        - name: postgres-for-redash
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      - name: server
        image: {{ .Values.image }}
        envFrom:
        - configMapRef:
            name: redash-cfg
        env:
        - name: REDASH_WEB_WORKERS
          value: "4"
        args: ["server"]
        lifecycle:
          postStart:
            exec:
              command: [ "/bin/sh", "-c", "/app/bin/docker-entrypoint create_db" ]
        ports:
        - containerPort: {{ .Values.server.port }}
          name: redash
      - name: scheduler
        image: {{ .Values.image }}
        envFrom:
        - configMapRef:
            name: redash-cfg
        env:
        - name: QUEUES
          value: "celery"
        - name: WORKERS_COUNT
          value: "1"
        args: ["scheduler"]
      - name: scheduled-worker
        image: {{ .Values.image }}
        envFrom:
        - configMapRef:
            name: redash-cfg
        env:
        - name: QUEUES
          value: "scheduled_queries,schemas"
        - name: WORKERS_COUNT
          value: "1"
        args: ["worker"]
      - name: adhoc-worker
        image: {{ .Values.image }}
        envFrom:
        - configMapRef:
            name: redash-cfg
        env:
        - name: QUEUES
          value: "queries"
        - name: WORKERS_COUNT
          value: "2"
        args: ["worker"]
```


Please, see redash.yaml in the above helm chart for more details: https://github.com/cloudcheflabs/dataroaster/blob/master/components/redash/chart/templates/redash.yaml
