### DISCUSSION TITLE
HashiCorp Vault Integration on Redash Failing - adding ENV VAR overriding ENTRYPOINT / CMD

### DISCUSSION THREAD

**Discussion by abin-aot** [getredash/redash#5941] [Q&A]
Hi Friends,

I am integrating HashiCorp Vault to my existing Redash instances on Openshift(Kubernetes). As part of the I am have secret injection as per [Vault documentation here](https://developer.hashicorp.com/vault/docs/platform/k8s/injector/examples#environment-variable-example) and they suggestion to add ENV VAR overriding the ENTRYPOINT . I am doing same things on my other PODS for Redis, Patroni - DB and it works fine. But not with REDASH - Why so ? Sample part from yaml is below . the `ENVAR1` is not getting created on the POD. In reality I am passing the out of secret file with an array of `env vars and its value` on it. For the sake of simplicity I created a single env var overriding the  ENTRYPOINT /CMD - 

```
          command:
            - /bin/sh
            - '-c'
          ports:
            - containerPort: 5000
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
         
          args:
            -  export ENVAR1="1" &&  /app/bin/docker-entrypoint server
```
