### DISCUSSION TITLE
redash works baaaaad in kubernetes

### DISCUSSION THREAD

**Discussion by esselesse** [getredash/redash#5969] [General]
Hi all! (it was wednesday dudes)
I have three problems with my redash service that i have in kubernetes pod.

1) it throws 502 gateway error almost every request or link click. so execution, saving script or even opening pages are total headache, i need to refresh pages and execute scripts many times
<img width="500" alt="image" src="https://user-images.githubusercontent.com/5176168/230219524-6084db28-f9eb-4d87-9a08-79d9a412ffac.png">.  
same with query saving - just an error "query could not be saved" every 2 out of 3 requests (clicks on Save button).  

2) (i think that the 1) depends on this) - redash-server does not stop creating web-workers. moreover, there is NO information in logs about why workers are stopping. totally. even on debug-level - no errors.
<img width="712" alt="image" src="https://user-images.githubusercontent.com/5176168/230217719-b3565e38-9fc2-478c-bf0a-2fc6b87ee24c.png">

3) i cannot import 'requests' module for python script - but it is installed in pod. 
<img width="775" alt="image" src="https://user-images.githubusercontent.com/5176168/230216926-96c5b22a-5385-4778-8eba-ddc12dde6eaf.png">
<img width="1488" alt="image" src="https://user-images.githubusercontent.com/5176168/230217093-1cb27084-acd0-41a6-ba3e-0ffc58d2f46b.png">
moreover, there is python 2.7 - that's weird. and if i try to (re)uninstall it - pod crashes, because every web worker from server need it somehow. if that worker crashes -> pod crashes.

my deployment:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redash
  template:
    metadata:
      labels:
        app: redash
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: "tmp-storage"
          emptyDir:
            sizeLimit: "500Mi"
      containers:
        - name: redash-web
          image: redash/redash
          args: ["server"]
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 512Mi
          ports:
            - name: redash-http
              containerPort: 5000
            - name: redash-server
              containerPort: 5678
          env:
            - name: REDASH_LOG_LEVEL
              value: WARN
            - name: REDASH_DATABASE_URL
              value: postgres://redash:redash@private.local:5432/redash <- pg is up in different pod
            - name: REDASH_REDIS_URL
              value: "redis://:password!@redis:6379/0" <- redis is up in different pod
            - name: REDASH_WEB_WORKERS
              value: "4"
            - name: REDASH_GUNICORN_TIMEOUT
              value: "60"
            - name: PYTHONUNBUFFERED
              value: "0"
            - name: REDASH_COOKIE_SECRET
              value: "nanitsecretlongonehere"
            - name: REDASH_HOST
              value: "redash"
            - name: REDASH_NAME
              value: "redash"
            - name: REDASH_MAIL_SERVER
              value: "email"
            - name: REDASH_MAIL_PORT
              value: "587"
            - name: REDASH_MAIL_USERNAME
              value: "smtp-user"
            - name: REDASH_MAIL_PASSWORD
              value: "smtp-password"
            - name: REDASH_MAIL_DEFAULT_SENDER
              value: "redash@redash.com"
            - name: REDASH_ADDITIONAL_QUERY_RUNNERS
              value: "redash.query_runner.python"
        - name: redash-scheduled-worker
          image: redash/redash
          args: ["worker"]
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 512Mi
          env:
            - name: REDASH_LOG_LEVEL
              value: DEBUG
            - name: REDASH_DATABASE_URL
              value: postgres://redash:redash@private.local:5432/redash
            - name: REDASH_REDIS_URL
              value: "redis://:password!@redis:6379/0"
            - name: REDASH_COOKIE_SECRET
              value: "nanitsecretlongonehere"
            - name: WORKERS_COUNT
              value: "1"
            - name: QUEUES
              value: "schemas,scheduled_queries"
            - name: PYTHONUNBUFFERED
              value: "0"
            - name: REDASH_ADDITIONAL_QUERY_RUNNERS
              value: "redash.query_runner.python"
        - name: redash-adhoc-worker
          image: redash/redash
          args: ["worker"]
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 512Mi
          env:
            - name: REDASH_LOG_LEVEL
              value: DEBUG
            - name: REDASH_DATABASE_URL
              value: postgres://redash:redash@private.local:5432/redash
            - name: REDASH_REDIS_URL
              value: "redis://:password!@redis:6379/0"
            - name: REDASH_COOKIE_SECRET
              value: "nanitsecretlongonehere"
            - name: WORKERS_COUNT
              value: "2"
            - name: QUEUES
              value: "queries"
            - name: PYTHONUNBUFFERED
              value: "0"
            - name: REDASH_ADDITIONAL_QUERY_RUNNERS
              value: "redash.query_runner.python"
        - name: redash-scheduler
          image: redash/redash
          args: ["scheduler"]
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 512Mi
          env:
            - name: REDASH_LOG_LEVEL
              value: DEBUG
            - name: REDASH_DATABASE_URL
              value: postgres://redash:redash@private.local:5432/redash
            - name: REDASH_REDIS_URL
              value: "redis://:password!@redis:6379/0"
            - name: REDASH_COOKIE_SECRET
              value: "nanitsecretlongonehere"
            - name: WORKERS_COUNT
              value: "1"
            - name: QUEUES
              value: "celery"
            - name: PYTHONUNBUFFERED
              value: "0"
            - name: REDASH_ADDITIONAL_QUERY_RUNNERS
              value: "redash.query_runner.python"
---
apiVersion: v1
kind: Service
metadata:
  name: redash-service
spec:
  ports:
    - port: 80
      targetPort: 5000
      name: redash-http
    - port: 5678
      targetPort: 5678
      name: redash-server
  selector:
    app: redash
  type: ClusterIP

```

i made that from https://github.com/getredash/setup/blob/master/data/docker-compose.yml and https://github.com/nanit/redash-kubernetes/blob/master/kube/dep.yml with some customizations.

what is wrong here? am i missing something?
how could i get rid of 502's and make my python script imports that 'requests' module?
