### DISCUSSION TITLE
Clean kubernetes deployment file

### DISCUSSION THREAD

**Discussion by esselesse** [getredash/redash#5976] [General]
i wrote a kubernetes deployment yaml file.
hope that it will help someone.

https://github.com/esselesse/redash-kubernetes-deployment

**Comment by eradman** [comment]
Thank you @esselesse! This is a variation I am using (PostgreSQL is configured as an external service).

```yaml
Deployment
---
apiVersion: v1
kind: Service
metadata:
  name: redash
spec:
  clusterIP: None
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: redash
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redash
  labels:
    app: redash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redash
  template:
    metadata:
      labels:
        app: redash
    spec:
      containers:
        - name: redash-web
          image: redash/preview:latest
          ports:
            - name: redash-server
              containerPort: 5000
          envFrom:
            - configMapRef:
                name: redash-env
          args: ["server"]

        - name: redash-worker
          image: redash/preview:latest
          envFrom:
            - configMapRef:
                name: redash-env
          env:
            - name: WORKERS_COUNT
              value: "3"
          args: ["worker"]

        - name: redash-worker-periodic
          image: redash/preview:latest
          envFrom:
            - configMapRef:
                name: redash-env
          env:
            - name: WORKERS_COUNT
              value: "1"
            - name: QUEUES
              value: "periodic"
          args: ["worker"]

        - name: redash-scheduler
          image: redash/preview:latest
          envFrom:
            - configMapRef:
                name: redash-env
          args: ["scheduler"]

        - name: redis
          image: docker.io/redis:7-alpine
          ports:
            - name: redis
              containerPort: 6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redash-env
data:
  PYTHONUNBUFFERED: "0"
  REDASH_COOKIE_SECRET: "******"
  REDASH_DATABASE_URL: "postgres://pg2.lan,pg3.lan/redash?target_session_attrs=read-write&user=redash&password=****"
  REDASH_REDIS_URL: "redis://localhost:6379/0"
  REDASH_FEATURE_ALLOW_CUSTOM_JS_VISUALIZATIONS: "true"
  REDASH_MAIL_SERVER: vm.eradman.com
```

_Notes_

1. `clusterIP` is normally assigned a service proxy address. None allows CoreDNS to return the endpoint.
2. This deployment also sets up a worker dedicated to the periodic queue, which is required under heavy load to prevent Redis keys from incorrectly expiring.

_Initial setup_

```sh
alias redash-exec='kubectl exec -ti $(kubectl get pods -l app=redash -o name)'
redash-exec -- ./manage.py database create_tables
redash-exec -- ./manage.py db upgrade
redash-exec -- ./manage.py users create_root eradman@eradman.com Redash --password '******'
```
