### DISCUSSION TITLE
Deploying redash quickly through Docker

### DISCUSSION THREAD

**Discussion by Jengro777** [getredash/redash#6288] [General]
Create two files, `docker-compose.yml` and `env`, respectively, under the same directory named redash.

![image](https://github.com/getredash/redash/assets/35259040/689b5af9-b176-418f-9139-28594518a708)

docker-compose.yml:

```
networks:
  default:
    name: 1panel-network  # 设置网络名称，不设置会自动生成
    external: true

x-redash-service: &redash-service
  image: redash/redash:25.1.0
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: 3
  depends_on:
    - postgres
    - redis
  env_file: 
    - ./env
  restart: always
  deploy:
    resources:
      limits:
        cpus: "0.5"
        memory: 500M
      reservations:
        cpus: "0.05"
        memory: 20M

services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 10

  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 10

  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas,periodic,default"
      WORKERS_COUNT: 2

  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 4

  redis:
    image: redis:7.4.2-alpine
    container_name: redash-redis
    restart: always

  postgres:
    image: postgres:17.2-alpine
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    container_name: redash-postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file: 
      - ./env
    ports:
      - "5432:5432"
    restart: always

```

env:

- For good security, those values are supposed to be generated by the user and kept secure in that env file.
```
PYTHONUNBUFFERED=0
REDASH_LOG_LEVEL=INFO
REDASH_REDIS_URL=redis://redis:6379/0

REDASH_COOKIE_SECRET=xvyXYDAYgMNB1hbjJPrha95LkeXLArFP
#用于session加密
REDASH_SECRET_KEY=lfLqjWNNetKNU4gb1uTwPxukNPrunuey
#用于数据库字段值加密，例如数据源账户密码
POSTGRES_PASSWORD=wxK3u5spuoqI5gaogYdz0yMTkKtZilYy
REDASH_DATABASE_URL=postgresql://postgres:wxK3u5spuoqI5gaogYdz0yMTkKtZilYy@postgres/postgres
# POSTGRES_PASSWORD=123456
# REDASH_DATABASE_URL=postgresql://postgres:123456@postgres/redash
#开启自定义代码
REDASH_FEATURE_ALLOW_CUSTOM_JS_VISUALIZATIONS="true"
#开启特殊数据源
REDASH_ADDITIONAL_QUERY_RUNNERS="redash.query_runner.python"
# REDASH_ADDITIONAL_QUERY_RUNNERS="redash.query_runner.oracle,redash.query_runner.python"
#自动清除查询记录
REDASH_QUERY_RESULTS_CLEANUP_ENABLED="true"
REDASH_QUERY_RESULTS_CLEANUP_COUNT="10000"
REDASH_QUERY_RESULTS_CLEANUP_MAX_AGE="1"
```

Execute the following command in the same directory to create the database:
`docker compose run --rm server create_db`

In the directory to install Redash, execute the command :
`docker compose up -d`

Open http://127.0.0.1:5000/ to access Redash.

---
If this is your first time installing, opening http://127.0.0.1:5000 will display a prompt:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

This is because the Postgres database has not been created. Execute the following command in the same directory to create the database:

create the database:  `docker compose run --rm server create_db`
upgrade the database:   `docker-compose run --rm server manage db upgrade`

---
redash中文部署以及操作手册
操作手册： https://www.yuque.com/summer-l4v2u/pxnwqp/bqgt5n
部署文档：https://redash.dazdata.com/docs/opensource/opensouce_install/installer_introduce

**Comment by justinclift** [comment]
At some point in the next few weeks, we should really update the [setup](https://github.com/getredash/setup/) process to be super easy again. :smile:

**Reply by Jengro777** [reply]
Currently, I am busy with my own work, and many of my friends are stuck at the deployment stage. The community version of Redash has been locked down, so I will update it here to share with my friends.

**Reply by Jengro777** [reply]
Actually, many data analysis professionals use Windows operating system. What they need the most is an executable binary file with a UI interface to guide the database configuration. Currently, we may face difficulties in packaging Redash for Windows, Mac, and Linux. I am considering whether we can leverage wasmer to generate executable WebAssembly (wasm) binary files for Redash, in order to achieve cross-platform fast deployment.

**Reply by justinclift** [reply]
Interesting.  Those are some very good points that we'll need to think about.

For people using Ubuntu Linux, the `setup.sh` script should still work.  It'll install an older version of Redash though, which can be manually updated afterwards.

macOS and Windows needs more thinking about though, for end user installs anyway. :smile:

**Reply by remcoboerma** [reply]
For people using windows (and linux/mac), there is a marvelous piece of software called [multipass](https://multipass.run) from canonical. It's a *very* easy way to have a linux virtual machine all up and running without all the virtualization hassle that's usually included. It does come with (memory, cpu and very very minimal cognitive) overhead for sure, but it works with a machine's local preferred virtualisor out of the box. I use it on my linux develop desktops to not have docker intervene with my regular network and keeps things perfectly seperated.

**Comment by remcoboerma** [comment]
Despite the dutch comments, just ignore those. Here is my `docker-compose.yml` file: 
```yaml
version: '2.3'
# komt van https://github.com/GoodforGod/docker-compose-ultimate#Redash 
# want is een stuk moderner dan de v1 docker-compose file die meegeleverd wordt. dat integreert niet met onze 
# instellingen om andere databases te kunnen benaderen.  
# alle instellingen zijn verhuist naar de .env file
#
# ## databases benaderen. 
# 1. Laat services een port gebruiken die uniek is, onze shell scripts hebben daar support voor. 
# 2. stel UFW in om verkeer op die poort toe te laten: 
#    `sudo ufw allow from 172.0.0.0/8 to 172.0.0.0/8 port 5551 proto tcp`
#    dit stelt de dockers in staat om met elkaar te verbinden, zonder dat UFW deze verbinding
#    eruit kegelt, maar van buiten af zijn deze poorten niet bereikbaar. wel zo veilig. 
#
# 3. gebruik `host.docker.local` om verbinding te maken met de host vanuit redash, en gebruik
#    de poort om onderscheid te maken tussen de verschillende diensten/databases. 
#
# ## python toevoegen
# Volgens [deze uitleg](https://redash.io/help/data-sources/querying/python) hoef je alleen
# `REDASH_ADDITIONAL_QUERY_RUNNERS: "redash.query_runner.python"` toe te voegen aan je omgeving
#

networks:
  broker:
    # this network is shared with traefik as a reverse proxy. 
    # it should be shared *ONLY* with user-facing services. 
    # redash-server that is in this setup. 
    name: broker
    external: true


# Redash service template. requires the command mostly
x-redash-service: &service-template
  image: redash/redash:latest
  depends_on:
    - redash-redis
    - redash-postgres
  environment:
    REDASH_RATELIMIT_ENABLED: ${REDASH_RATELIMIT_ENABLED}
    REDASH_LOG_LEVEL: ${REDASH_LOG_LEVEL}
    REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
    REDASH_SECRET_KEY: ${REDASH_SECRET_KEY}
    REDASH_REDIS_URL: redis://redash-redis/0
    REDASH_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@redash-postgres/${POSTGRES_DB}
    REDASH_ADDITIONAL_QUERY_RUNNERS: redash.query_runner.python
    REDASH_FEATURE_ALLOW_CUSTOM_JS_VISUALIZATIONS: true
  extra_hosts:
    host.docker.internal: host-gateway
  restart: unless-stopped

services:
  redash-createdb:
    <<: *service-template
    command: create_db
    restart: no

  redash-server:
    <<: *service-template
    expose:
      - 5000
    depends_on:
      - redash-redis
      - redash-postgres
      - redash-createdb
    command: server
    networks:
      - default
      - broker
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${PROJECT}-server.loadbalancer.server.port=5000" # in case multipe ports are exposed, this label forces 5000
      - "traefik.http.routers.${PROJECT}-secure.tls=true"
      - "traefik.http.routers.${PROJECT}-secure.tls.certresolver=${CERTRESOLVER}"
      - "traefik.http.routers.${PROJECT}-secure.rule=Host(`${APPLICATION_NAME}.${HOSTING_DOMAIN}`)"
      - "traefik.docker.network=broker" # https://doc.traefik.io/traefik/providers/docker/#network


  redash-scheduler:
    <<: *service-template
    command: scheduler

  redash-worker:
    <<: *service-template
    command: worker

  redash-redis:
    image: redis
    restart: unless-stopped
    command: redis-server

  redash-postgres:
    image: postgres:13-alpine3.15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

```

it uses this `.env` file as a template: 
```bash
PYTHONUNBUFFERED=1
REDASH_RATELIMIT_ENABLED='false'
REDASH_LOG_LEVEL=INFO
REDASH_COOKIE_SECRET=secret-secret-secret-create-your-own-by-using-keepass-or-apg-on-lniux 
REDASH_SECRET_KEY=secret-secret-secret-create-your-own-by-using-keepass-or-apg-on-lniux 
POSTGRES_DB=postgres
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres-or-secret-secret-secret-create-your-own-by-using-keepass-or-apg-on-lniux
APPLICATION_NAME=redash
HOSTING_DOMAIN=domainname.tld 
PROJECT=redash
CERTRESOLVER=letsencrypt
```

I'll follow up with more documentation how this integrates with databases in other dockers (mind the firewall) and how to configure traefik in a separate docker-compose file to handle all incoming traffic and ssl-certificates automatically.
