### DISCUSSION TITLE
Alerting is not working (STATUS: UNKNOWN)

### DISCUSSION THREAD

**Discussion by jtallar-hu** [getredash/redash#6364] [Q&A] [answered]
Hi team! 

I'm having issues with the use of Redash alerts. They stay in Status Unknown, even after manually refreshing the referenced query. I tried re-creating the alert and changing the referenced query, but the status won't change.

I think this could be related to the update I've made from Redash v8 to Redash v10.1.0. But I can't tell for sure whether the alerts were working or not before in Redash v8 because I did not try using them until now. 

When I first updated, I missed the changes outlined for the `docker-compose.yml` file before. I just changed the Redash image reference, stopped, and recreated the Docker containers. I then tried applying all the necessary changes in the docker-compose file and re-creating the containers, but it won't fix the issue. I tried searching for any logs that could point to a cause, but I couldn't find anything.

All other Redash services and functionality seems to be working fine.

Below are the configuration details as of today, together with the alert configuration.

Many thanks!

## Deploy configuration details
I have an EC2 instance running in AWS with Redash.
**/opt/redash/docker-compose.yml**
```yml
version: "2"
x-redash-service: &redash-service
  image: redash/redash:10.1.0.b50633
  depends_on:
    - postgres
    - redis
  env_file: /opt/redash/env
  restart: always
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    <<: *redash-service
    command: scheduler
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
  worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "periodic emails default"
      WORKERS_COUNT: 1
  redis:
    image: redis:5.0-alpine
    restart: always
  postgres:
    image: postgres:9.6-alpine
    env_file: /opt/redash/env
    volumes:
      - /opt/redash/postgres-data:/var/lib/postgresql/data
    restart: always
  nginx:
    image: redash/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always

```

**/opt/redash/env**
```
PYTHONUNBUFFERED=0
REDASH_LOG_LEVEL=INFO
REDASH_REDIS_URL=redis://redis:6379/0
POSTGRES_PASSWORD=*****
REDASH_COOKIE_SECRET=*****
REDASH_SECRET_KEY=*****
REDASH_DATABASE_URL=postgresql://*****
REDASH_GOOGLE_CLIENT_ID=*****
REDASH_GOOGLE_CLIENT_SECRET=*****

REDASH_MAIL_SERVER=email-smtp.sa-east-1.amazonaws.com
REDASH_MAIL_PORT=587
REDASH_MAIL_USE_TLS=true
REDASH_MAIL_USE_SSL=true
REDASH_MAIL_USERNAME=*****
REDASH_MAIL_PASSWORD=*****
REDASH_MAIL_DEFAULT_SENDER=*****
```

## Alert configuration
<img width="985" alt="Screenshot 2023-08-10 at 14 30 02" src="https://github.com/getredash/redash/assets/97113156/e38631d2-58d3-48c9-b2cd-8170dd9043b6">

**Alert tester query**
```sql
SELECT 1
```

**Comment by jtallar-hu** [comment, marked as answer]
This has been solved by itself. Apparently, fixing the update steps solved this issue. I do not know why it took a few hours to work.

**Reply by sidharthramesh** [reply]
I have a similar issue. Alert does not update even after manually refreshing the query.

**Reply by eradman** [reply]
In the screenshot the query is scheduled to run every two weeks. To test the alert you need to set it to a short interval (every 1 or 5 minutes). The alert is only triggered when run on a schedule, so unfortunately running it manually does not change the alert state.

**Comment by ChrisGibb** [comment]
Hi, I'd like to update this page since it's the top result on Google when searching for this problem.

I copied a section of the docker-compose.yml that @jtallar-hu posted, however I modified it a bit.

The important part is this section:
![image](https://github.com/getredash/redash/assets/22681764/3bf6eefa-238c-47e1-afbb-f2b41c7470e9)

Notice how there are no commas separating the queue names.

I'm not sure if that's what caused things not to work for me. 

However in my case what I did was create separate workers for each queue:

```
  periodic_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "periodic"
      WORKERS_COUNT: 1
  emails_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "emails"
      WORKERS_COUNT: 1
  default_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "default"
      WORKERS_COUNT: 1
```

Then I went to the status page at `/admin/queries/jobs#queues`

Finally, I saw this huge number begin to decrease:

![image](https://github.com/getredash/redash/assets/22681764/a2b2ed52-374c-40aa-bc5e-7adebbc166b0)

After waiting some time, eventually, the alert went to status ok.

I hope this helps someone in the future.
