### DISCUSSION TITLE
Listing trino schema list is not available in redash dashborad.

### DISCUSSION THREAD

**Discussion by kyeongjun-dev** [getredash/redash#6384] [Q&A]
Hi, I have a problem that listing trino schema in redash dashboard.

Everything is working well.
But after add data source(trino) in redash dashborad, I have an error like below.
error message is "Schema refresh failed. Please try again later."
![image](https://github.com/getredash/redash/assets/107162956/75254df6-fdb4-4cfd-8a58-cd9660c71b26)

And I found that when I refresh the New Query menu, Trino try to run query like below.
query is
```
SELECT table_schema, table_name, column_name
FROM information_schema.columns
WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
```
![image](https://github.com/getredash/redash/assets/107162956/49774743-7ed9-48e2-87bd-6bffd3fbe993)

Other queries is working well.
- show catalogs
![image](https://github.com/getredash/redash/assets/107162956/3e3efdba-a5a8-43dc-adc9-de655e4ec0d2)

- show schemas from mysql_1
![image](https://github.com/getredash/redash/assets/107162956/e1902f4d-8920-48ff-9fdf-502c9d3aa2bb)

- show tables from mysql_1.information_schema
![image](https://github.com/getredash/redash/assets/107162956/90ea1b0c-c981-4ab3-83bb-b392b9576711)

What I missed?

Trino version : 422
Redash version : https://github.com/getredash/contrib-helm-chart (latest version)

In installing Trio, I used below values.yaml (Only edited additionalCatalogs)
```
accessControl: {}
additionalCatalogs:
  mysql_1: |-
    connector.name=mysql
    connection-url=jdbc:mysql://mysql-1.mysql-1.svc.cluster.local:3306
    connection-user=root
    connection-password=root
  mysql_2: |-
    connector.name=mysql
    connection-url=jdbc:mysql://mysql-2.mysql-2.svc.cluster.local:3306
    connection-user=root
    connection-password=root
additionalConfigProperties: {}
additionalExchangeManagerProperties: {}
additionalLogProperties: {}
additionalNodeProperties: {}
auth: {}
coordinator:
  additionalConfigFiles: {}
  additionalExposedPorts: {}
  additionalJVMConfig: {}
  affinity: {}
  annotations: {}
  config:
    memory:
      heapHeadroomPerNode: ""
    query:
      maxMemoryPerNode: 1GB
  jvm:
    gcMethod:
      g1:
        heapRegionSize: 32M
      type: UseG1GC
    maxHeapSize: 8G
  labels: {}
  livenessProbe: {}
  nodeSelector: {}
  readinessProbe: {}
  resources: {}
  tolerations: []
env: []
envFrom: []
eventListenerProperties: {}
image:
  pullPolicy: IfNotPresent
  repository: trinodb/trino
  tag: latest
imagePullSecrets:
- name: registry-credentials
initContainers: {}
kafka:
  mountPath: /etc/trino/schemas
  tableDescriptions: {}
secretMounts: []
securityContext:
  runAsGroup: 1000
  runAsUser: 1000
server:
  autoscaling:
    enabled: false
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
  config:
    authenticationType: ""
    http:
      port: 8080
    https:
      enabled: false
      keystore:
        path: ""
      port: 8443
    path: /etc/trino
    query:
      maxMemory: 4GB
  coordinatorExtraConfig: ""
  exchangeManager:
    baseDir: /tmp/trino-local-file-system-exchange-manager
    name: filesystem
  log:
    trino:
      level: INFO
  node:
    dataDir: /data/trino
    environment: production
    pluginDir: /usr/lib/trino/plugin
  workerExtraConfig: ""
  workers: 1
service:
  port: 8080
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: false
  name: ""
worker:
  additionalConfigFiles: {}
  additionalExposedPorts: {}
  additionalJVMConfig: {}
  affinity: {}
  annotations: {}
  config:
    memory:
      heapHeadroomPerNode: ""
    query:
      maxMemoryPerNode: 1GB
  jvm:
    gcMethod:
      g1:
        heapRegionSize: 32M
      type: UseG1GC
    maxHeapSize: 2G
  labels: {}
  livenessProbe: {}
  nodeSelector: {}
  readinessProbe: {}
  resources: {}
  tolerations: []
```

And, redash (It is only for local testing)
```
redash:
  cookieSecret: UrIS1S9iGRugV+sNVwfIUkA+6sGL8w7wxc3c7TmgZOM=
  secretKey: YaYgKG7+94GeEJPPL+EKSfneXKW8+7C2fgFeno8N3oY=
postgresql:
  postgresqlPassword: B9iSD3cpj+g1mgiO0aneo17ymGgHWYLd3d5qucEFC8E=
redis:
  password: wIvnNUdqT5ybWFozFL8LrBL2kxg50oNGeSznqrZmnsA=
```
