### DISCUSSION TITLE
Unable to read Arabic content from queries

### DISCUSSION THREAD

**Discussion by mahmoudelatma** [getredash/redash#6395] [Q&A] [answered]
Hi everyone,

I have a Redash installation via the following Docker-compose.yml file on windows server machine, from within the application Homepage after registration, I've created a Datasource to connect to a MS Sql Server DB which have a collation of _Arabic_100_CI_AI_ ,
I used UTF-8 as character set and TDS version 7.0 as defaults, however the queries result set doesn't show Arabic letters it shows something like this "ÇáãÔÑæÚ", looking forward to your support..

The Docker-compose.yml

```
version: '2'

x-redash-service: &redash-service
  image: redash/redash:latest
  depends_on:
    - postgres
    - redis
  env_file: redash.env
  restart: always

services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
      LC_ALL: C.UTF-8

  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1

  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1

  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2

  redis:
    image: redis:latest
    restart: always

  postgres:
    image: postgres:latest
    env_file: redash.env
    restart: always
    networks:
      - default

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always

```
 
and the redash.env file is as follows:
```
REDASH_HOST=http://localhost/redash
PYTHONUNBUFFERED=0
REDASH_LOG_LEVEL=INFO
REDASH_REDIS_URL=redis://redis:6379/0
POSTGRES_PASSWORD=
POSTGRES_HOST_AUTH_METHOD=trust
REDASH_COOKIE_SECRET=####
REDASH_SECRET_KEY=####
REDASH_DATABASE_URL=postgresql://postgres@postgres/postgres
```
