### DISCUSSION TITLE
Hosting redash in Docker container on windows with IIS reverse proxy

### DISCUSSION THREAD

**Discussion by mahmoudelatma** [getredash/redash#6665] [Q&A] [answered]
Hello community,

I'm trying to host Redash instance on windows server served with IIS alongside with other applications, I hosted Redash on a docker container inside the windows machine which was working as expected from port 5000. 

My issue started to appear when I was trying to expose Redash URL under a specific path (https://mydomain.com/redash) within my IIS website containing the SSL certificate, the IIS website already contains an inbound reverse proxy rule to rewrite requests on the root to a different application hosted on port 8080 with outbound rule to rewrite URLs matching http://mydomain.com:8080 to https://mydomain.com which is working as expected, So I've added another inbound reverse proxy rule to match only /redash requests to be rewritten to http://mydomain.com:5000 the complete website configuration file is as follows:

> <configuration>
    <system.webServer>
        <urlCompression doStaticCompression="false" doDynamicCompression="false" />
        <rewrite>
            <rules>
                <clear />
                <rule name="ReverseProxyInboundRule2" stopProcessing="true">
                    <match url="^redash/(.*)" />
                    <conditions logicalGrouping="MatchAll" trackAllCaptures="false" />
                    <action type="Rewrite" url="http://mydomain.com:5000/{R:1}" logRewrittenUrl="true" />
                </rule>
                <rule name="ReverseProxyInboundRule1" stopProcessing="true">
                    <match url="(.*)" />
                    <conditions logicalGrouping="MatchAll" trackAllCaptures="false" />
                    <action type="Rewrite" url="http://mydomain.com:8080/{R:1}" logRewrittenUrl="true" />
                </rule>
            </rules>
            <outboundRules>
                <rule name="ReverseProxyOutboundRule1" preCondition="ResponseIsHtml1">
                    <match filterByTags="A, Form, Img" pattern="^http(s)?://mydomain.com:8080/(.*)" />
                    <action type="Rewrite" value="http{R:1}://mydomain.com/{R:2}" />
                </rule>
                <preConditions>
                    <preCondition name="ResponseIsHtml1">
                        <add input="{RESPONSE_CONTENT_TYPE}" pattern="^text/html" />
                    </preCondition>
                </preConditions>
            </outboundRules>
        </rewrite>
    </system.webServer>
</configuration>

What I faced was when I requested https://mydomain.com/redash , the request got served by the other application under port 8080, after some investigations, I found out that it's a base URL configuration as I traced the request which was as follows:

https://mydomain.com/redash -> got rewritten an redirected correctly to http://mydomain.com:5000 which issued the following redirect request.
https://mydomain.com/login?next=http%3A%2F%2Fmydomain.com%3A5000%2F -> "no /redash path" which caused it to be rewritten to the other application using the other rule. 

I also tried to request /login page directly by requesting https://mydomain.com/redash/login which caused the html itself to be served correctly but without any images, css, or js files as all of them was requested by the url https://mydomain.com/static/js which caused it to be requested from the other application.

My redash docker-compose file is as follows: 

```
version: '2'

x-redash-service: &redash-service
  image: redash/redash:latest
  depends_on:
    - postgres
    - redis
  env_file: redash.env
  restart: always

services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
      LC_ALL: C.UTF-8
      REDASH_HOST: https://mydomain.com/redash
      REDASH_PROXIES_COUNT: 2
    volumes:
      - ./data:/app/data

  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1

  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1

  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2

  redis:
    image: redis:latest
    restart: always

  postgres:
    image: postgres:latest
    env_file: redash.env
    restart: always
    networks:
      - default
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 4567:8080

  nginx:
    image: nginx:latest
    ports:
      - "4000:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
```
the 
```
REDASH_HOST: https://mydomain.com/redash
REDASH_PROXIES_COUNT: 2
```
was one of my trials, I tried with and without them

and my redash.env file is as follows:

```
REDASH_HOST=https://mydomain.com/redash
PYTHONUNBUFFERED=0
REDASH_LOG_LEVEL=INFO
REDASH_REDIS_URL=redis://redis:6379/0
POSTGRES_PASSWORD=pgPassword
POSTGRES_HOST_AUTH_METHOD=trust
REDASH_COOKIE_SECRET=redash-selfhosted
REDASH_SECRET_KEY=redash-selfhosted
REDASH_DATABASE_URL=postgresql://postgres@postgres/postgres
REDASH_PROXIES_COUNT=2
```
I'm unable to make sure that the REDASH_HOST configuration parameter is correctly set and I don't know where the redash instance got the url https://mydomain.com/ from.

any help or suggestions will be very helpful.

Thanks and best regards.
