### DISCUSSION TITLE
can't access Redash EC2 server behind AWS Load Balancer

### DISCUSSION THREAD

**Discussion by anandkummari** [getredash/redash#6711] [Q&A]
I setup redash server on my private EC2 using https://redash.io/help/open-source/setup#setup-redash-instance-setup. When I do port forwarding from ec2 to my local machine, redash home page works fine.
When I put redash server behind ALB I get the following error. I have pomerium service which forwards requests to my private load balancer.

Redash Server Logs from `docker logs redash_server_1` : 
`[2024-01-17 07:06:18,088][PID:12][INFO][metrics] method=GET path=/ endpoint=redash_index status=302 content_type=text/html; charset=utf-8 content_length=351 duration=0.57 query_count=0 query_duration=0.00`

I tried changing nginx.conf under `opt/redash/nginx` and updated `docker-compose.yml`.
nginx.conf file is

```
upstream redash {
    server redash:5000;
}

server {
    listen      80;
    listen [::]:80;
    listen 443 default ssl;

    access_log /var/log/nginx/rd.access.log;

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;

        proxy_pass       http://redash;
    }
}

```
and my docker-compose.yml file is

```
version: "2"
x-redash-service: &redash-service
  image: redash/redash:8.0.0.b32245
  depends_on:
    - postgres
    - redis
  env_file: /opt/redash/env
  restart: always
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
  redis:
    image: redis:5.0-alpine
    restart: always
  postgres:
    image: postgres:9.6-alpine
    env_file: /opt/redash/env
    volumes:
      - /opt/redash/postgres-data:/var/lib/postgresql/data
    restart: always
  nginx:
    image: redash/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    links:
      - server:redash
    volumes:
      - /opt/redash/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
```

Can someone help me resolving this issue.
