### DISCUSSION TITLE
Connecting Redash to ClickHouse with SSL

### DISCUSSION THREAD

**Discussion by matthieukhl** [getredash/redash#6984] [Q&A]
Hi everyone,
I’m having trouble establishing a secure connection between Redash and ClickHouse using SSL.

Here’s a summary of my setup and the issue I’m facing:

#### Docker-Compose Configuration
```
version: "2"

x-redash-service: &redash-service
  image: redash/redash:latest
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: 3
  depends_on:
    - postgres
    - redis
  env_file: .env
  restart: always

services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 10
    volumes:
      - /path/to/certificates:/SSL

  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 10

  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas,periodic,default"
      WORKERS_COUNT: 2

  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 4

  redis:
    image: redis:6.0-alpine
    container_name: redash-redis
    restart: always

  postgres:
    image: postgres:13-alpine
    container_name: redash-postgres
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_secure_password
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
```

#### Environment file (.env)
```
PYTHONUNBUFFERED=0
REDASH_LOG_LEVEL=INFO
REDASH_REDIS_URL=redis://redis:6379/0

REDASH_COOKIE_SECRET=your_secure_cookie_secret
REDASH_SECRET_KEY=your_secure_secret_key

POSTGRES_PASSWORD=my_secure_password
REDASH_DATABASE_URL=postgresql://postgres:my_secure_password@postgres/postgres

REDASH_FEATURE_ALLOW_CUSTOM_JS_VISUALIZATIONS=true
REDASH_ADDITIONAL_QUERY_RUNNERS=redash.query_runner.python,redash.query_runner.oracle

REDASH_QUERY_RESULTS_CLEANUP_ENABLED=true
REDASH_QUERY_RESULTS_CLEANUP_MAX_AGE=7
```

#### Connection String in Redash
```
clickhouse://username:password@hostname:port/database?protocol=https&secure=true&sslmode=verify-full&ca_certs=/SSL/ca.pem&client_cert=/SSL/client-cert.pem&client_key=/SSL/client-key.pem
```

#### Issue :
I am able to start the Redash services without any issues.
The SSL certificates are mounted correctly in the /SSL directory within the Docker container.
However, when I try to test the connection to ClickHouse from Redash, I get an InvalidSchema error.

I have verified that the certificates and keys are present and correctly mounted in the container. Despite this, I am unable to establish a secure connection.
Has anyone faced a similar issue or have any suggestions on how to resolve this? Any help would be greatly appreciated!
Thank you!
