### DISCUSSION TITLE
Queries not refreshing; possibly no background processes running?

### DISCUSSION THREAD

**Discussion by jonahgreenthal** [getredash/redash#7074] [Q&A]
Since I upgraded to Redash 10, my scheduled queries have not been refreshing.

I've tried a ton of troubleshooting steps found by searching this repo's issues and discussions, as well as things I found on other sites, but nothing seems to help.

Here's my `/admin/status`:
![image](https://github.com/user-attachments/assets/fc757d06-51c6-4eba-94d3-f9b63b482eeb)
The queues keep growing. I've purged them several times; one was in the tens of thousands before I purged.

Here's `/admin/queries/jobs`:
![image](https://github.com/user-attachments/assets/9ee9c4b3-67e7-40d1-926d-c1e679f70c4d)
![image](https://github.com/user-attachments/assets/12b7ec7a-7e48-4290-9edb-0cc0a681b6d2)
![image](https://github.com/user-attachments/assets/6bac9dc2-28c1-4c69-9a7b-0b376e8cd4f7)
![image](https://github.com/user-attachments/assets/929863bb-c46d-4065-80d4-04e5d0e2b53a)

`/admin/queries/outdated` produces an error; I don't know if that's a hint.

Here's my `docker-compose.yml`. The commented-out lines are from previous troubleshooting attempts:
```yml
version: "2"
x-redash-service: &redash-service
  image: redash/redash:10.1.0.b50633
  depends_on:
    - postgres
    - redis
  env_file: /opt/redash/env
  restart: always
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    <<: *redash-service
    command: scheduler
    depends_on:
      - server
#    environment:
#      QUEUES: "celery"
#      WORKERS_COUNT: 1
  scheduled_worker:
    <<: *redash-service
    command: worker
    depends_on:
      - server
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 5
  adhoc_worker:
    <<: *redash-service
    command: worker
    depends_on:
      - server
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
#  worker:
#    <<: *redash-service
#    command: worker
#    environment:
#      QUEUES: "periodic emails default"
#      WORKERS_COUNT: 5
  redis:
#    image: redis:5.0-alpine
    image: redis:7-alpine
    restart: unless-stopped
  postgres:
#    image: postgres:9.6-alpine
    image: pgautoupgrade/pgautoupgrade:latest
    env_file: /opt/redash/env
    volumes:
      - /opt/redash/postgres-data:/var/lib/postgresql/data
    restart: always
  nginx:
    image: redash/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    links:
      - server:redash
    volumes:
      - /opt/redash/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /opt/redash/nginx/certs:/etc/letsencrypt
      - /opt/redash/nginx/certs-data:/data/letsencrypt
    restart: always
  worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "periodic,emails,default"
      WORKERS_COUNT: 5
```

It's running on an EC2 t2.small instance with a bunch of swap space because I know Redash 10 is memory-hungry. Here's `top`:
```
top - 05:16:50 up 9 min,  2 users,  load average: 0.00, 0.33, 0.33
Tasks: 142 total,   1 running, 141 sleeping,   0 stopped,   0 zombie
%Cpu(s):  6.2 us,  0.0 sy,  0.0 ni, 93.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   1955.8 total,     73.1 free,   1634.4 used,    248.3 buff/cache
MiB Swap:   2048.0 total,   1325.5 free,    722.5 used.    157.1 avail Mem 
```

I'd really appreciate any help with this. I'm at a loss.
