### ISSUE TITLE
Vertica connection error with psycopg2 in OSX

### ISSUE THREAD

**Issue by heoa** [getredash/redash#3033]
### Issue Summary

`Error running query: (psycopg2.IntegrityError) null value in column "data" violates not-null constraint DETAIL: Failing row contains (12, 1, 2, ----------------------------ca, SELECT * FROM myDB.myTable LIMIT 100, null, 3.1010000000000000, 2018-10-31 13:00:55.640993+00).
`
### Steps to Reproduce

1. Install with Docker on OSX: https://gist.github.com/deepak365/3316270abce892370414bee232f31551
2. Make a vertica connection and you will get psycopg2 integrityError

### Technical details:

* Redash Version: v5.0.2
* Browser/OS: Chrome Version 70.0.3538.77 (Official Build) (64-bit)
* How did you install Redash: built with Docker following the instructions https://gist.github.com/deepak365/3316270abce892370414bee232f31551

**Comment by ljluestc** [comment]
```

version: "2"
services:
  server:
    image: redash/redash:5.0.2  # Update to 'latest' if upgrading
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    environment:
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
  worker:
    image: redash/redash:5.0.2
    command: worker
    depends_on:
      - postgres
      - redis
    environment:
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
  redis:
    image: redis:5.0-alpine
  postgres:
    image: postgres:9.6-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​
```
