### ISSUE TITLE
MySQL Connector SSL not working

### ISSUE THREAD

**Issue by tr37ion** [getredash/redash#3455]
### Issue Summary

Adding data source SSL certs is a bit difficult. 
### Steps to Reproduce

1. Add a new MySQL data source
2. After manually adding a `docker volume` to one host user's home dir in `docker-compose.yml`:
```
...
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
   volumes:
      - /home/user/redash/certs:/sslcerts
....
```
3. Pressing `Test Connection` shows green `Success` box and press `Save`
4. Add a new Query
5. Pressing the blue `Play` button in the lower/right corner of Query edit results in an error message:
 `Error running query: SSL connection error: SSL_CTX_set_default_verify_paths failed`

### Suggestion

Please make it possible to upload SSL certs in the data source input section.

### Technical details:

* Redash Version: Redash 6.0.0+b8537 (4780bd9c)
* Browser/OS: Firefox Nightly 67.0a1 (2019-02-01) (64-bit)
* How did you install Redash: Setup.sh `from https://github.com/getredash/redash/tree/master/setup`
