### ISSUE TITLE
Users list: Disable button pushed beyond scroll when many groups are used

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3521]
![image](https://user-images.githubusercontent.com/71468/53695932-35fd6d80-3dca-11e9-8d01-fc5b429891f8.png)

(you can see a live version on https://redash-preview.netlify.com)

**Comment by ranbena** [comment]
Maybe this can be just tackled by a few css overrides for labels in table:
```css
.items-list .label-tag {
  display: inline-block;
  max-width: 135px;
}
```
Which results in:
![screen shot 2019-03-07 at 10 13 10](https://user-images.githubusercontent.com/486954/53941783-b3262c80-40c1-11e9-8325-d2d32712b076.png)
