### ISSUE TITLE
Queries search is not working on release/7.0.x

### ISSUE THREAD

**Issue by veerkat** [getredash/redash#3602]
### Issue Summary

I try building docker image with the redash dockerfile and start by docker-compose. But queries search is not working

### Steps to Reproduce

![Untitled](https://user-images.githubusercontent.com/6704470/54521288-93d2ad80-49a5-11e9-9794-94572b6698d0.gif)

Check out the queries table and find that search_vector is null.
![1](https://user-images.githubusercontent.com/6704470/54521423-de542a00-49a5-11e9-9f37-5b5923042973.png)

### Technical details:

* Redash Version: release/7.0.x
* Browser/OS: Chrome Mac
* How did you install Redash: redash setup

**Comment by arikfr** [comment]
How did you build the database?

**Comment by veerkat** [comment]
> How did you build the database?

use redash/setup/docker-compose.yml

```
postgres:
  image: postgres:9.5.6-alpine
  env_file: /opt/redash/env
  volumes:
    - /opt/redash/postgres-data:/var/lib/postgresql/data
  restart: always
```
