### ISSUE TITLE
Schema refresh using beta v9 with MySQL not working

### ISSUE THREAD

**Issue by lawrenceelitzer** [getredash/redash#5115]
### Issue Summary

Using mysql & redash beta v9 the schema will not refresh. Seems a few others are also having the same issue on the discussion forums but haven't seen any workarounds or further discussion on it. 

 - https://discuss.redash.io/t/schema-refresh-failed-for-mysql-data-source/3880/8
 - https://discuss.redash.io/t/redash-v9-cant-refresh-schema/6950

We are currently on the latest BETA version... We needed the BETA version due to security vulnerabilities in previous versions.

### Steps to Reproduce

1. Change schema and try to refresh in redash 💥 

### Technical details:

* Redash Version: v9 beta
* How did you install Redash: Docker

**Comment by gabrieldutra** [comment]
@lawrenceelitzer did you install it directly on v9-beta or you made upgrades from other Redash versions?

**Comment by elitzer2** [comment]
@gabrieldutra good question it was an upgrade.

**Comment by gabrieldutra** [comment]
Sorry for the late answer here 😅, so, do you have any other data source in which the Schema Refresh works?

I believe that for most people in the forum the issue is on upgrading as we had a few [extra instructions](https://github.com/getredash/redash/blob/master/CHANGELOG.md#upgrading) for the process. Anyway, this is the query we use to get the schema for MySQL:

```sql
SELECT col.table_schema as table_schema,
        col.table_name as table_name,
        col.column_name as column_name
FROM `information_schema`.`columns` col
WHERE col.table_schema NOT IN ('information_schema', 'performance_schema', 'mysql', 'sys');
```

Can you check if it executes?

**Comment by lawrenceelitzer** [comment]
Thanks for the info. That query does execute just fine. And we did follow those extra steps, here's the docker file in its current form:

```
version: '2'
x-redash-service: &redash-service
  image: redash/redash:9.0.0-beta.b42121
  depends_on:
    - postgres
    - redis
  env_file: /opt/redash/env
  restart: always
  volumes:
    - /home/ubuntu/redash_resources:/home/redash/resources
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 2
  scheduler:
    <<: *redash-service
    command: scheduler
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries"
      WORKERS_COUNT: 1
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
  redis:
    image: redis:5.0-alpine
    restart: always
  postgres:
    image: postgres:9.5.6-alpine
    env_file: /opt/redash/env
    volumes:
      - /opt/redash/postgres-data:/var/lib/postgresql/data
    restart: always
  nginx:
    image: redash/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
  worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "periodic emails default"
      WORKERS_COUNT: 1
```

If it matters any, we are running Ubuntu 18.04.3 with MySQL 8.0.15 and we are using an RDS read replica.

When I tail the logs I see this entry that it seemed successful but then you see the front-end just polling the job and it eventually times out and doesn't update on the frontend:

```
[2020-09-09 14:36:10,150][PID:1181][INFO][metrics] method=GET path=/api/data_sources/2/schema endpoint=datasourceschemaresource status=200 content_type=application/json content_length=139 duration=16.69 query_count=6 query_duration=16.84
```
