### ISSUE TITLE
When refreshing, the modification of my query results will not take effect

### ISSUE THREAD

**Issue by woozhijun** [getredash/redash#5642]
When we upgrade v8.0.0 to v10.0.0 for a period of time. I found the following problems:

### step 1
> Create new query for redash bi.

### step 2 
> Execute query and save. eg:
Have results to  3 columns.

### step 3
> When I modify the query content，Return the query result to 5 columns. And save query.

### step 4
> When refreshing，the modification of my query results will not take effect，It's still the last result.

### step 5
> When I continue to execute it twice, again refresh, this time take effect.

## Do you have the same question？[CRITITAL]  Thanks!

Docker-compose.yml  contents：
```
version: '2.2'
x-redash-service: &redash-service
  image: redash/redash:10.0.0.b50363
  depends_on:
    - postgres
    - redis
  env_file: /deploy/redash_10.0/env
  restart: always
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 6
      REDASH_THROTTLE_LOGIN_PATTERN: "500/hour"
  scheduler:
    <<: *redash-service
    command: scheduler
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries schemas"
      WORKERS_COUNT: 8
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 8
  worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "periodic emails default"
      WORKERS_COUNT: 8
  redis:
    image: redis:5.0-alpine
    restart: always
  postgres:
    ports:
      - "5432:5432"
    image: postgres:9.5-alpine
    env_file: /deploy/redash_10.0/env
    volumes:
      - /home/data/bi_postgres:/var/lib/postgresql/data
    restart: always
```
