### ISSUE TITLE
Update every 1 minute does not work fine

### ISSUE THREAD

**Issue by nrukavkov** [getredash/redash#5752]
Hello. Please help me to solve problem. I can't understand why Queries with Refresh Schedule 1 minute or 5 minutes is never executed automatically. This are no errors in logs. 

`http://redash/admin/queries/jobs` page shows Started Jobs = 0 and Queued Jobs = 0

My `docker-compose.yaml`

```
version: "2.2"
x-redash-service: &redash-service
  image: redash/redash:10.1.0.b50633
x-redash-environment: &redash-environment
  REDASH_LOG_LEVEL: "INFO"
  REDASH_REDIS_URL: "redis://redis:6379/0"
  REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
  REDASH_RATELIMIT_ENABLED: "false"
  REDASH_ENFORCE_CSRF: "true"
  REDASH_HOST: "https://redash.myhost.com"
  REDASH_COOKIE_SECRET: "11111"
services:
  server:
    <<: *redash-service
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "10.10.10.123:15000:5000"
      - "10.10.10.123:15678:5678"
    environment:
      <<: *redash-environment

  scheduler:
    <<: *redash-service
    command: worker
    depends_on:
      - server
    environment:
      <<: *redash-environment
      QUEUES: "celery"
      WORKER_COUNT: 1

  scheduled_worker:
    <<: *redash-service
    command: worker
    depends_on:
      - server
    environment:
      <<: *redash-environment
      #QUEUES: "scheduled_queries schemas"
      #WORKER_COUNT: 1

  adhoc_worker:
    <<: *redash-service
    command: worker
    depends_on:
      - server
    environment:
      <<: *redash-environment
      QUEUES: "queries"
      WORKER_COUNT: 2

  worker:
    <<: *redash-service
    command: worker
    depends_on:
      - server
    environment:
      <<: *redash-environment
      QUEUES: "periodic emails default"
      WORKER_COUNT: 1

  redis:
    image: redis:3-alpine
    restart: unless-stopped
  postgres:
    image: postgres:9.5-alpine
    ports:
      - "10.10.10.123:15432:5432"
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
```

What did I wrong while configuring?
