### ISSUE TITLE
aarch64 support

### ISSUE THREAD

**Issue by emilburzo** [getredash/redash#5765]
### Issue Summary

I'm trying to run redash on a Raspberry Pi 4B. 

From the existing topics I could find it seems like this should be supported:
- https://discuss.redash.io/t/arm64-support-in-the-docker-images/3480/8
- https://github.com/getredash/redash/issues/5684
- https://github.com/getredash/redash/pull/5687

But I must be doing something wrong as I still can't seem to get it to work:

> standard_init_linux.go:228: exec user process caused: exec format error

### Steps to Reproduce

```bash
# docker run --rm redash/redash:preview
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error
```

### Technical details:

* Redash Version: `preview` docker hub tag
* Browser/OS: Ubuntu 20.04.4 LTS
* How did you install Redash: docker

**Comment by teascanner** [comment]
Any update on this?

**Comment by justinclift** [comment]
@guidopetri has been doing some work and testing around this.  Things don't completely work "out of the box" yet, but we shouldn't be a long way off.

**Comment by guidopetri** [comment]
I've found that the redash image builds, but a) we haven't implemented it in an auto-image build and b) I haven't verified full functionality

**Comment by guidopetri** [comment]
Update here - we tried building the image in the CI but it took way too long (it hit the Github Actions apparent limit of 6 hours). We'll have to rethink our approach to building the image automatically.

That being said, as mentioned above, I _was_ able to build this on a raspberry pi locally in ~1h, and it seems to run fine. So if you're able to build it locally, that is an option for now.

**Comment by AndrewChubatiuk** [comment]
arm64 support was added in https://github.com/getredash/redash/pull/6674

**Comment by justinclift** [comment]
@AndrewChubatiuk Lets try and get some of the people who've asked for this to verify it works for them before we close the issue. :smile:

@emilburzo @teascanner Are either of you still around and interested in trying this out? :smile:

Along these lines, it sounds like @square-li is attempting this exact thing too.  Lets make sure it all works properly.

**Comment by justinclift** [comment]
@mxmua Any interest in having a go at this too? :smile:

**Comment by justinclift** [comment]
@mogopz @fliplafe @bomwo @junhodo @yasuno0327 @AmitArie Any interest in trying this out as well? :smile:

**Comment by smmathews** [comment]
I've verified the fix on Raspberry Pi 5
`pi@pi5:~ $ docker run -e REDASH_COOKIE_SECRET=cookie --rm redash/redash:preview
Starting Redash Server in a dev mode
[2024-04-17 19:59:07,310][PID:1][INFO][xmlschema] Resource 'XMLSchema.xsd' is already loaded
 * Debug mode: on
[2024-04-17 19:59:08,130][PID:1][INFO][werkzeug] WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.17.0.2:5000
`

**Comment by justinclift** [comment]
Awesome, thanks heaps for checking @smmathews. :smile:

@AndrewChubatiuk Looks like you've really helped out a bunch with the aarch64/arm64 support too.  Well done. :smile:

**Comment by florian-besser** [comment]
This issue seems to have regressed @justinclift @AndrewChubatiuk 
If I check out https://hub.docker.com/r/redash/redash/tags I can only see AMD64 as a supported arch (for all tags)
Using an M1 mac with ARM architecture and `docker pull redash/redash:preview` yields error `Error response from daemon: no match for platform in manifest: not found`

Could it be this was somehow removed after the PR was merged?

**Comment by justinclift** [comment]
Uh oh.  Yeah it's probably related to that (!). :frowning:

**Comment by pauljura** [comment]
Hi team, is there any activity on this? Does this issue need to be re-opened?

I am trying to move our current Redash deployment to new ARM-based AWS EC2s and cannot pull a compatible image.

**Comment by lucydodo** [comment]
Maybe I'll have time to look at this this weekend. :)

**Comment by lucydodo** [comment]
Well, I had a quick look at it over the weekend and it takes a long time to build ARM64 in emulation, so I can't commit it yet. I'll try to figure out how to improve the speed, just give me a little more time :)

**Comment by lucydodo** [comment]
Yes, but the ARM64 runner is still only available to Team and Enterprise plan users.
I have managed to reduce the speed somewhat with other methods and am currently in the middle of final testing.

Tomorrow is the start of August, so new snapshots will be created and deployed via Docker Hub, so I'm hoping to have this done by the end of the day. I successfully created an ARM64 image in my last test, so it shouldn't be a problem.

**Comment by mmospanenko** [comment]
Oh, I did'n know about it, always use self-hosted runners. Recently I optimized our Django app (enough big, tons of deps) and base image (os) has significant impact on build time, just FYI
Thank you for the great job!

**Comment by lucydodo** [comment]
A PR has been created with an improvement to address this issue: #7094 
It's in the review phase and I'll let you know when it's finished and an image has been created. :)

**Comment by justinclift** [comment]
The above mentioned PR has been merged. :smile:

**Comment by lucydodo** [comment]
<img width="1171" alt="Screenshot 2024-08-03 at 04 29 52" src="https://github.com/user-attachments/assets/67e06339-fda1-40be-ab6c-cf41885b7d3b">

> https://hub.docker.com/layers/redash/preview/24.08.1-dev/images/sha256-56a45bfefb2382aebafbd00bdbeedb7b22a1a935459b8e6980cffd9bb3a0e79f?context=explore

New preview images with ARM64 support in Docker Hub are now available! 🚀 
Could you please check it out and let us know? :)

**Comment by pauljura** [comment]
This looks like it might work, but the nginx service isn't working. Any chance you can build `redash/nginx` for ARM64 as well? :)

**Comment by lucydodo** [comment]
Hi @pauljura, Thank you for your confirmation.
I don't think it should be difficult, but I don't know where those image builds are coming from.*
I'll ask the other maintainers and try to fix Nginx to support the AArch64 platform as well.

>*: I've just joined the team, so I'm not familiar with the codebase, infrastructure, etc. yet :)

**Comment by lucydodo** [comment]
> https://hub.docker.com/layers/redash/nginx/latest/images/sha256-4335d3d7bc99e72375b6b94452d1bbe5382e5db9eb9b6e4d17e29264c1e4fe8e?context=explore

@pauljura Nginx docker images for ARM64 platforms are also available frow now.
Why don't you give it a try and let us know. :)

**Comment by pauljura** [comment]
@lucydodo Hi, I got it working, no issues so far. Thank you!

PS. I also had to follow all the steps in the 'How to upgrade' docs, this was my first time migrating Redash to a new server, but eventually figured everything out and it works.

**Comment by lucydodo** [comment]
Glad to hear it's resolved, I'll close the issue :)

**Comment by zentavr** [comment]
> Well, I had a quick look at it over the weekend and it takes a long time to build ARM64 in emulation, so I can't commit it yet. I'll try to figure out how to improve the speed, just give me a little more time :)

We used to attach custom AWS Codebuild nodes into Github Actions in order to build ARM64 images. The process looks like:
1. Build an image for amd64
2. Build an image for arm64
3. Merge them with a single manifest

**Comment by lucydodo** [comment]
>Well, I had a quick look at it over the weekend and it takes a long time to build ARM64 in emulation, so I can't commit it yet. I'll try to figure out how to improve the speed, just give me a little more time :)

GitHub has finally released free-tier ARM64 runners for public repositories today. I tested it right away, but unfortunately, there seems to be an issue with `actions/setup-node@v4`, so it looks like I can’t apply it right away.
The same issue has already been reported, so I’ll test it again and write a PR as soon as it’s resolved. :)

**Comment by zentavr** [comment]
Hello @lucydodo.
What kind of issues do you have when building the image on ARM64 with `actions/setup-node@v4`?

I have a couple of internal node.js projects here internally and we are building them in pretty adequate time.

**Comment by lucydodo** [comment]
Hi @zentavr ,I received the following error:
`Error: Error: EACCES: permission denied, open '/home/runneradmin/.config/yarn'`

It seems that the current ARM64 runners do not have proper permissions for the path inside `$HOME/.config`.
Other projects accessing `.config` also encounther the same issue and fail.

Related:
- https://github.com/orgs/community/discussions/148648#discussioncomment-11858717
- https://github.com/actions/setup-node/issues/1202

**Comment by emilburzo** [comment]
I just finished migrating from docker-compose to my rPi k3s cluster and I can also confirm that everything works!

---

Translating from docker-compose to kubernetes took a while, so just in case it helps anyone else, here's what I ended up with:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: redash
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redash
  namespace: redash
data:
  PYTHONUNBUFFERED: "0"
  REDASH_LOG_LEVEL: "INFO"
  REDASH_REDIS_URL: "redis://redis:6379/0"
  REDASH_HOST: "..."
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redash
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redash
  labels:
    run: redis
spec:
  ports:
    - port: 6379
      protocol: TCP
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: redash
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: redash/redash:25.8.0
          imagePullPolicy: Always
          args: ["server"]
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: redash
            - secretRef:
                name: redash
          env:
            - name: REDASH_WEB_WORKERS
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: redash
  labels:
    run: server
spec:
  ports:
    - port: 5000
      protocol: TCP
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: redash
  labels:
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: scheduler
          image: redash/redash:25.8.0
          imagePullPolicy: Always
          args: ["scheduler"]
          envFrom:
            - configMapRef:
                name: redash
            - secretRef:
                name: redash
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-scheduled
  namespace: redash
  labels:
    app: worker-scheduled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-scheduled
  template:
    metadata:
      labels:
        app: worker-scheduled
    spec:
      containers:
        - name: worker-scheduled
          image: redash/redash:25.8.0
          imagePullPolicy: Always
          args: ["worker"]
          envFrom:
            - configMapRef:
                name: redash
            - secretRef:
                name: redash
          env:
            - name: QUEUES
              value: "scheduled_queries,schemas"
            - name: WORKERS_COUNT
              value: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-adhoc
  namespace: redash
  labels:
    app: worker-adhoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-adhoc
  template:
    metadata:
      labels:
        app: worker-adhoc
    spec:
      containers:
        - name: worker-adhoc
          image: redash/redash:25.8.0
          imagePullPolicy: Always
          args: ["worker"]
          envFrom:
            - configMapRef:
                name: redash
            - secretRef:
                name: redash
          env:
            - name: QUEUES
              value: "queries"
            - name: WORKERS_COUNT
              value: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-general
  namespace: redash
  labels:
    app: worker-general
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-general
  template:
    metadata:
      labels:
        app: worker-general
    spec:
      containers:
        - name: worker-general
          image: redash/redash:25.8.0
          imagePullPolicy: Always
          args: ["worker"]
          envFrom:
            - configMapRef:
                name: redash
            - secretRef:
                name: redash
          env:
            - name: QUEUES
              value: "periodic emails default"
            - name: WORKERS_COUNT
              value: "1"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redash
  namespace: redash
spec:
  rules:
  - host: ...
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: server
            port:
                number: 5000
```

Approach:
- separate kubernetes namespace to keep everything clean
- configMap to avoid repeating the environment variables
- secrets for... secrets
- kubernetes internal dns for discovering redis
- (I'm using an external postgres instance, so I didn't add one here)
