### ISSUE TITLE
Date Fetching Issue

### ISSUE THREAD

**Issue by arunbalaji04** [getredash/redash#5936]
I am trying to fetch the data with 100K but it is not visible after fetched the data. but it was worked as well till yesterday.

**Comment by lucasfcnunes** [comment]
Can you elaborate more on your issue?

**Comment by arunbalaji04** [comment]
Hi,

Below the shared table contains the 100K rows but we can't fetch the data.
It is getting a blank page after fetching it.

[image: image.png]



Thanks,
Arunbalaji K

**Comment by myonlylonely** [comment]
Maybe you can look into this. https://github.com/getredash/redash/issues/5613

**Comment by lucasfcnunes** [comment]
I remember having this issue too so I am using in my helm chart.
```yaml
env:
  ...
  GUNICORN_CMD_ARGS: --timeout=300
  ...
```

*in a compose.yaml with the same structure of the one in the root of this project (https://github.com/getredash/redash/blob/master/docker-compose.yml):
```yaml
x-redash-environment: &redash-environment
  ...
  REDASH_GUNICORN_TIMEOUT: 300
  ...
```

Maybe you will need a greater timeout but I don't think it's likely :)
