### ISSUE TITLE
Cannot login with AzureAD SAML when user does't have Last Name

### ISSUE THREAD

**Issue by Zuhdan** [getredash/redash#6358]
### Issue Summary

User cannot login when does not have last name, and error occure on the server like this:

![image](https://github.com/getredash/redash/assets/6513361/a71bdcc4-f74c-4237-a8e0-ca82077817f5)

### Steps to Reproduce

1. sign-in using saml azure ad 
2. redirect error 302

### Technical details:

* Redash Version: 8.0.0.b32245
* How did you install Redash: docker-compose
my docker compose: 

```
version: "2"
x-redash-service: &redash-service
  image: redash/redash:8.0.0.b32245
  depends_on:
    - postgres
    - redis
  env_file: /opt/redash/env
  restart: always
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5002:5000"
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
  redis:
    image: redis:5.0-alpine
    restart: always
  postgres:
    image: postgres:9.6-alpine
    env_file: /opt/redash/env
    volumes:
      - /opt/redash/postgres-data:/var/lib/postgresql/data
    restart: always
  nginx:
    image: redash/nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
```
