### ISSUE TITLE
SchedulerWorker doesn't refresh query #6773

### ISSUE THREAD

**Issue by ognjen-it** [getredash/redash#6806]
### Issue Summary

I have a problem with the scheduler worker. It will work if I set it to run every 1 minute or 1 hour, but if I set every week it doesn't refresh the query.

Discussions #6773

### Steps to Reproduce

1. Build docker image from source (docker build -t ognjenit/redash:24.2.0-dev)
2. Deploy redash with helm chart (helm -n redash upgrade --install redash redash/redash -f ./values.yaml --version 3.0.1)

Values file:
```
redash:
  cookieSecret: TestPassword123123
  secretKey: TestPassword123123
  host: https://redash.example.com/
  mailDefaultSender: user@example.com
  mailServer: email-smtp.eu-west-1.amazonaws.com
  mailPort: 587
  mailUsername: mailUsername
  mailPassword: mailPassword
  mailUseSsl: false
  mailUseTls: true
postgresql:
  postgresqlPassword: TestPassword123123
redis:
  password: TestPassword123123
image:
  repository: ognjenit/redash
  tag: 24.02.0-dev
scheduledWorker:
  env:
    REDASH_LOG_LEVEL: "DEBUG"
scheduler:
  env:
    REDASH_LOG_LEVEL: "DEBUG"
```

### Technical details:

* Redash Version: Latest, manual built from source (master). +
* Browser/OS: Chrome Version Version 122.0, Mac 14.2.1
* How did you install Redash: With [helm chart](https://github.com/getredash/contrib-helm-chart)
