### ISSUE TITLE
CSV data source does not work with address in the same network

### ISSUE THREAD

**Issue by mjmikulski** [getredash/redash#7216]
### Issue Summary

This is similar to #4193 but with following differences:
- #4790 was merged
- I added `REDASH_ENFORCE_PRIVATE_IP_BLOCK` flag
- It is about CSV not JSON

### Steps to Reproduce

0. Add the flag to `compose.yaml` as below
```yaml
mmikulski /opt/redash $ cat compose.yaml
x-redash-service: &redash-service
  image: redash/redash:10.1.0.b50633
  depends_on:
    - postgres
    - redis
  env_file: /opt/redash/env
  restart: always
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "4000:4000"
    environment:
      REDASH_WEB_WORKERS: 4
      REDASH_ENFORCE_PRIVATE_IP_BLOCK: "false"  # <- HERE
...
```
1. `docker compose up -d`
2. Add CSV data source from UI.
3. New query that uses CSV data source:
```
url: "http://10.....csv"
```
as suggested [here](https://redash.io/help/data-sources/querying/csv-excel-files/).

4. Get the following error message:
```
Error running query: Can't query private addresses.
```

### Technical details:

* Redash Version: 10.1.0.b50633
* Browser/OS: Chrome/MacOS (redash: Ubuntu 22.04)
* How did you install Redash: from docker image
