### ISSUE TITLE
Docker-compose not working

### ISSUE THREAD

**Issue by ebertti** [getredash/redash#837]
I had to fix the docker-compose-example to:

```yaml
redash:
  image: redash/redash
  ports:
    - "5000:5000"
  links:
    - redis
    - postgres
  environment:
    REDASH_STATIC_ASSETS_PATH: "../rd_ui/app/"
    REDASH_LOG_LEVEL: "INFO"
    REDASH_REDIS_URL: "redis://redis:6379/0"
    REDASH_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
    REDASH_COOKIE_SECRET: "veryverysecret"
    REDASH_GOOGLE_APPS_DOMAIN: "aa"

redis:
  image: redis:2.8
  ports:
    - "6379:6379"

postgres:
  image: postgres:9.3
  ports:
    - "5234:5234"
  volumes:
   - /opt/postgres-data:/var/lib/postgresql/data

redash-nginx:
  image: redash/nginx
  ports:
    - "80:80"
  links:
    - redash
```

When it start to conect everything, I got this two erros:

![image](https://cloud.githubusercontent.com/assets/140394/13154407/f1c85802-d65f-11e5-9390-ce8658f08b3e.png)

![image](https://cloud.githubusercontent.com/assets/140394/13154478/4764162a-d660-11e5-8a60-c4a79350c7c6.png)

I think some create database command is missing on docker creation.

**Comment by joaoleite** [comment]
I am also facing this exact problem.

Can anyone help?

:(

**Comment by arikfr** [comment]
The first problem happens because you set the assets path to `rd_ui/app` which doesn't exist in the Docker image. Just remove the `REDASH_STATIC_ASSETS_PATH` env variable from the Docker compose file.

As for the database, you need to create it. Try using this script: https://github.com/getredash/redash/blob/master/setup/docker/create_database.sh. It wasn't tested enough yet, but should work.

**Comment by ebertti** [comment]
Hi!

Taking about the missing index template:

```yml
redash:
  image: redash/redash
  ports:
    - "5000:5000"
  links:
    - redis
    - postgres
  environment:
    REDASH_LOG_LEVEL: "INFO"
    REDASH_REDIS_URL: "redis://redis:6379/0"
    REDASH_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
    REDASH_COOKIE_SECRET: "veryverysecret"
    REDASH_GOOGLE_APPS_DOMAIN: "aa"
```

I'm still getting same error:

![image](https://cloud.githubusercontent.com/assets/140394/13155762/6d0bf1a8-d666-11e5-9f9e-ec71adafb3f8.png)
